import Head from "next/head";
import { useState, useEffect, SetStateAction } from "react";
import VipArea from "../components/VipArea";
import axios from "axios";

export default function Home() {
  const [randomPick, setRandomPick] = useState<string>(
    "Clicca qui sotto per iniziare!"
  );
  const [list, setList] = useState([]);
  const [newComment, setNewComment] = useState("");
  const [notify, setNotify] = useState(false);
  const [journeyArea, setJourneyArea] = useState(true);
  const [vipArea, setVipArea] = useState(false);

  //const dummyList = ["first", "second", "three", "four", "five"];

  async function getListData() {
    const response = await axios.get(
      "https://mybase-72f82-default-rtdb.europe-west1.firebasedatabase.app///comments.json"
    );
    setList(Object.values(response.data));
  }

  useEffect(() => {
    getListData();
  }, []);

  function randomChoice(someList: { title: string }[]) {
    const randomNumber = Math.random() * someList.length;
    let choice;

    for (let i = 0; i < randomNumber; i++) {
      choice = someList[i].title;
    }
    return choice;
  }

  async function handleSubmit() {
    try {
      if (newComment.toLowerCase() === "vip area") {
        setJourneyArea(false);
        setVipArea(true);
        return;
      }
      if (newComment !== "" && newComment !== "vip area") {
        axios.post(
          "https://mybase-72f82-default-rtdb.europe-west1.firebasedatabase.app///comments.json",
          { title: newComment }
        );

        setNotify(true);
        setTimeout(() => setNotify(false), 2000);
      }
    } catch (e) {
      console.log(e);
    }
    setNewComment("");
  }

  return (
    <>
      <Head>
        <title>Emerald Journey</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/pokeball.ico" />
      </Head>
      {journeyArea && (
        <div className="box">
          <div className="top-part">
            <h1>Emerald Journey</h1>
            <div className="random-pick">{randomPick}</div>
            <button
              className="button"
              onClick={() => {
                let choice = randomChoice(list) || "";
                setRandomPick("rullo di tamburi...");
                setTimeout(() => setRandomPick(choice), 3000);
              }}
            >
              Let&apos;s begin!
            </button>
          </div>
          <div className="input-container">
            <textarea
              placeholder="Write a new comment here..."
              className="input"
              rows={6}
              onChange={(e) => {
                e.preventDefault();
                setNewComment(e.target.value);
              }}
              value={newComment}
            />
            <button className="submit-button" onClick={() => handleSubmit()}>
              Submit
            </button>
            {notify && <div className="notify">Sent Succesfully!</div>}
          </div>
        </div>
      )}
      {vipArea && <VipArea />}
    </>
  );
}
